/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.erp;

import com.erp.DAO.ChartOfAccountsDAO;
import com.erp.DTO.ChartOfAccountsDTO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.apache.poi.ss.usermodel.Workbook;
/**
 *
 * @author Zaw Min Htwe
 */
public class ChartOfAccountsPage extends javax.swing.JPanel {

    /**
     * Creates new form ChartOfAccountsPage
     */
    public ChartOfAccountsPage() {
        initComponents();
        loadDataSet();
        //showDataToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        accCodeTxt = new javax.swing.JTextField();
        accNameTxt = new javax.swing.JTextField();
        accTypeCombo = new javax.swing.JComboBox<>();
        accStatusCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        exportExcelBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        saveBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        coaTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        accTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ASSET", "EQUITY", "LIABILITY", "REVENUE", "EXPENSE" }));

        accStatusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "In Active" }));

        jLabel1.setText("Account Code");

        jLabel2.setText("Account Name");

        jLabel3.setText("Account Type");

        jLabel4.setText("Status");

        exportExcelBtn.setText("Export");
        exportExcelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportExcelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(accCodeTxt)
                    .addComponent(accNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(accTypeCombo, 0, 109, Short.MAX_VALUE)
                    .addComponent(accStatusCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(exportExcelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(accCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exportExcelBtn))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(accNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accStatusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saveBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(427, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(deleteBtn)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        coaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Account Code", "Account Name", "Account Type", "Status"
            }
        ));
        coaTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                coaTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(coaTable);
        if (coaTable.getColumnModel().getColumnCount() > 0) {
            coaTable.getColumnModel().getColumn(0).setMinWidth(60);
            coaTable.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
       if (accCodeTxt.getText().trim().isEmpty() || accNameTxt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill Code and Name!", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    ChartOfAccountsDTO dto = new ChartOfAccountsDTO();
    dto.setAccount_code(accCodeTxt.getText().trim());
    dto.setAccount_name(accNameTxt.getText().trim());
    dto.setAccount_type(accTypeCombo.getSelectedItem().toString());
    dto.setIs_active(accStatusCombo.getSelectedItem().toString());

    ChartOfAccountsDAO dao = new ChartOfAccountsDAO();
    if (dao.insert(dto)) {
        JOptionPane.showMessageDialog(this, "Account Saved Successfully.");
        loadDataSet();
        clearFields();
        //showDataToTable();
    } else {
        JOptionPane.showMessageDialog(this, "Save Failed!", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int selectedRow = coaTable.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a row to delete!", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this record?", "Confirm", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        DefaultTableModel model = (DefaultTableModel) coaTable.getModel();
        int id = Integer.parseInt(model.getValueAt(selectedRow, 0).toString());

        ChartOfAccountsDAO dao = new ChartOfAccountsDAO();
        if (dao.delete(id)) {
            JOptionPane.showMessageDialog(this, "Account Deleted.");
            loadDataSet();
           // showDataToTable();
        } else {
            JOptionPane.showMessageDialog(this, "Delete Failed!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_deleteBtnActionPerformed
    private int coaId;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        if (coaId == 0) {
            JOptionPane.showMessageDialog(this, "Please select for Update Account");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to update this record?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {

        ChartOfAccountsDTO chartOfAccountsDTO = new ChartOfAccountsDTO();
        chartOfAccountsDTO.setAccount_id(coaId);
        chartOfAccountsDTO.setAccount_code(accCodeTxt.getText());
        chartOfAccountsDTO.setAccount_name(accNameTxt.getText());
        chartOfAccountsDTO.setAccount_type(accTypeCombo.getSelectedItem().toString());
        chartOfAccountsDTO.setIs_active(accStatusCombo.getSelectedItem().toString());
        
        ChartOfAccountsDAO chartOfAccountsDAO = new ChartOfAccountsDAO();
        boolean success = chartOfAccountsDAO.update(chartOfAccountsDTO);
        
        if (success) {
            loadDataSet();
            coaId = 0;
            JOptionPane.showMessageDialog(this, "Chart of Account Updated Successfully");
            
        }else{
            JOptionPane.showMessageDialog(this, "Update Failed");
        }
        }   
    }//GEN-LAST:event_jButton3ActionPerformed

    private void coaTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coaTableMouseClicked
        int row = coaTable.getSelectedRow();
        coaId = Integer.parseInt(coaTable.getValueAt(row, 0).toString());
       accCodeTxt.setText(coaTable.getValueAt(row, 1).toString());
       accNameTxt.setText(coaTable.getValueAt(row, 2).toString());
       accTypeCombo.setSelectedItem(coaTable.getValueAt(row, 3).toString());
        accStatusCombo.setSelectedItem(coaTable.getValueAt(row, 4).toString());
        
        
    }//GEN-LAST:event_coaTableMouseClicked

    private void exportExcelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportExcelBtnActionPerformed
        // 🚀 EXPORT TO EXCEL FUNCTION (Apache POI သုံး၍ Excel -------> poi,poi-ooxml,poi-ooxml,xmlbeans,dom)

    javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
    fileChooser.setDialogTitle("Specify a file to save Excel");
    fileChooser.setSelectedFile(new java.io.File("ChartOfAccounts.xlsx"));
    
    int userSelection = fileChooser.showSaveDialog(this);
    if (userSelection == javax.swing.JFileChooser.APPROVE_OPTION) {
        java.io.File fileToSave = fileChooser.getSelectedFile();
        
        XSSFWorkbook workbook = new org.apache.poi.xssf.usermodel.XSSFWorkbook();
       try (java.io.FileOutputStream out = new java.io.FileOutputStream(fileToSave)) {
            
            org.apache.poi.ss.usermodel.Sheet sheet = workbook.createSheet("Chart of Accounts");
            
            // Header Row ပြုလုပ်ခြင်း
            org.apache.poi.ss.usermodel.Row headerRow = sheet.createRow(0);
            String[] columns = {"Account Code", "Account Name", "Account Type", "Status"};
            for (int i = 0; i < columns.length; i++) {
                org.apache.poi.ss.usermodel.Cell cell = headerRow.createCell(i);
                cell.setCellValue(columns[i]);
            }
            
            // JTable ထဲမှ ဒေတာများကို Loop ပတ်၍ Excel ထဲသို့ ထည့်သွင်းခြင်း
            DefaultTableModel model = (DefaultTableModel) coaTable.getModel();
            for (int i = 0; i < model.getRowCount(); i++) {
                org.apache.poi.ss.usermodel.Row row = sheet.createRow(i + 1);
                row.createCell(0).setCellValue(model.getValueAt(i, 0).toString());
                row.createCell(1).setCellValue(model.getValueAt(i, 1).toString());
                row.createCell(2).setCellValue(model.getValueAt(i, 2).toString());
                row.createCell(3).setCellValue(model.getValueAt(i, 3).toString());
            }
            
            // Auto-size columns
            for (int i = 0; i < columns.length; i++) {
                sheet.autoSizeColumn(i);
            }
            
            workbook.write(out);
            JOptionPane.showMessageDialog(this, "Excel Exported Successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Export Failed: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    }//GEN-LAST:event_exportExcelBtnActionPerformed

    private void showDataToTable() {
    DefaultTableModel model = (DefaultTableModel) coaTable.getModel();
    model.setRowCount(0); // ဇယားဟောင်းကို ရှင်းထုတ်ခြင်း
    
    ChartOfAccountsDAO dao = new ChartOfAccountsDAO();
    List<ChartOfAccountsDTO> list = dao.getAllAccounts();
    
    for (ChartOfAccountsDTO dto : list) {
        model.addRow(new Object[]{
            dto.getAccount_id(),
            dto.getAccount_code(),
            dto.getAccount_name(),
            dto.getAccount_type(),
             dto.getIs_active()
                
        });
    }
    }

        public void loadDataSet() {
        try {
            ChartOfAccountsDAO categoryDAO = new ChartOfAccountsDAO();
            coaTable.setModel(categoryDAO.getCOATableModel());
        } catch (Exception e) {
        }
    }
    
    private void clearFields() {
    accCodeTxt.setText("");
    accNameTxt.setText("");
    accTypeCombo.setSelectedIndex(0);
    accStatusCombo.setSelectedIndex(0);
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accCodeTxt;
    private javax.swing.JTextField accNameTxt;
    private javax.swing.JComboBox<String> accStatusCombo;
    private javax.swing.JComboBox<String> accTypeCombo;
    private javax.swing.JTable coaTable;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton exportExcelBtn;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
