/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.erp;

import com.erp.DAO.CustomerDAO;
import com.erp.DAO.JournalDAO;
import com.erp.DAO.SupplierDAO;
import com.erp.DTO.ComboIdName;
import com.erp.DTO.JournalDTO;
import java.awt.Component;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Zaw Min Htwe
 */
public class JournalPage extends javax.swing.JPanel {

   
  private JournalDAO jDAO = new JournalDAO();
  private CustomerDAO customerDAO = new CustomerDAO();
  private SupplierDAO supplierDAO = new SupplierDAO();
    private JComboBox<ComboIdName> customerComboBox;
    private JComboBox<ComboIdName> supplierComboBox;
  
  
    public JournalPage() {
        initComponents();
        
        
        //to show database data for combobox
        javax.swing.table.TableColumn accountName = journalTable.getColumnModel().getColumn(1);
        javax.swing.JComboBox<ComboIdName> comboBox = new javax.swing.JComboBox<>();
        List<ComboIdName> accountList = jDAO.getAccountNamesFromDB();
        for (ComboIdName item : accountList) {
            comboBox.addItem(item);
            
        }
         accountName.setCellEditor(new javax.swing.DefaultCellEditor(comboBox));
        setupDynamicDropdowns();
        debitOrCreditClose();
         
          }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        deleteRowBtn = new javax.swing.JButton();
        newRowBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        saveBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        journalTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("To Date");

        jLabel2.setText("From Date");

        jButton4.setText("Search");

        deleteRowBtn.setText("Delete Row");
        deleteRowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRowBtnActionPerformed(evt);
            }
        });

        newRowBtn.setText("New Row");
        newRowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRowBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteRowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newRowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(deleteRowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(newRowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");

        updateBtn.setText("Update");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(591, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        journalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Account", "Cup/ Sup", "Voucher No", "Description", "Debit", "Credit"
            }
        ));
        journalTable.setRowHeight(40);
        jScrollPane1.setViewportView(journalTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 927, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void newRowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRowBtnActionPerformed
       newRow();    
    }//GEN-LAST:event_newRowBtnActionPerformed

    private void deleteRowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRowBtnActionPerformed
       int selectedRow = journalTable.getSelectedRow();
       if(selectedRow >=0){
           DefaultTableModel model = (DefaultTableModel) journalTable.getModel();
           model.removeRow(selectedRow);
       }
    }//GEN-LAST:event_deleteRowBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) journalTable.getModel();
        int rowCount = model.getRowCount();
        
        if(rowCount == 0 ){
            JOptionPane.showMessageDialog(this, "There have no data in Journal","Waring",JOptionPane.WARNING_MESSAGE);
            return;

        }
        
         int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to save?", "Confirm", JOptionPane.YES_NO_OPTION);

        if(confirm == JOptionPane.YES_OPTION){
            JournalDAO journalDAO = new JournalDAO();
            int successCount = 0;
            
            for(int i = 0; i < rowCount ; i ++){
                JournalDTO journalDTO = new JournalDTO();
                
                try {
                    Object dateObj = model.getValueAt(i, 0);
                    if(dateObj != null){
                        java.text.SimpleDateFormat format = new java.text.SimpleDateFormat("dd-MM-yyyy");
                        java.util.Date utilDate = format.parse(dateObj.toString().trim());
                        journalDTO.setEntryDate(new java.sql.Date(utilDate.getTime()));
                    }  
                } catch (Exception e) {
                }
                
                Object accObj = model.getValueAt(i, 1);
                String accountName = accObj != null ? accObj.toString().trim() : "";
                if (accObj instanceof ComboIdName) {
                    ComboIdName selectedAccount = (ComboIdName) accObj;
                    int accountId = selectedAccount.getId();
                    //journalTable.setValueAt(accountId, i, 1);
                    journalDTO.setAccountId(accountId);
                } else if (accObj != null) {
                    String accName = accObj.toString().trim();
                }
                
                Object cellValue = journalTable.getValueAt(i, 2);
                if (cellValue != null) {
                    if (cellValue instanceof ComboIdName) {
                        if (accountName.equalsIgnoreCase("Receivable")) {
                            ComboIdName selectedCustomer = (ComboIdName) cellValue;
                            int customerId = selectedCustomer.getId();
                           // journalTable.setValueAt(customerId, i, 2);
                            journalDTO.setCustomerId(customerId); // 🚀 မှတ်ချက်- ဤနေရာတွင် DTO သို့ ထည့်ရန် ကျန်နေခဲ့၍ ဖြည့်ပေးထားပါသည်
                        } else if (accountName.equalsIgnoreCase("Payable")) {
                            ComboIdName selectedSupplier = (ComboIdName) cellValue;
                            int supplierId = selectedSupplier.getId();
                          //  journalTable.setValueAt(supplierId, i, 2);
                            journalDTO.setSupplierId(supplierId); // 🚀 မှတ်ချက်- ဤနေရာတွင် DTO သို့ ထည့်ရန် ကျန်နေခဲ့၍ ဖြည့်ပေးထားပါသည်
                        }
                    }
                }
                
                Object voucherObj = model.getValueAt(i, 3);
                journalDTO.setVoucherNo(voucherObj != null ? voucherObj.toString().trim() : "");

                Object descObj = model.getValueAt(i, 4);
                journalDTO.setDescription(descObj != null ? descObj.toString().trim() : "");

                Object debitObj = model.getValueAt(i, 5);
                journalDTO.setDebit(debitObj != null && !debitObj.toString().isEmpty() ? Double.parseDouble(debitObj.toString().trim()) : 0.0);

                Object creditObj = model.getValueAt(i, 6);
                journalDTO.setCredit(creditObj != null && !creditObj.toString().isEmpty() ? Double.parseDouble(creditObj.toString().trim()) : 0.0);

                
                boolean success = journalDAO.insertJournalDetails(journalDTO);                
                if (success) {
                    successCount++; // သိမ်းတာ အောင်မြင်ရင် ၁ တိုးမည်
                }
               
                System.out.println(journalDTO.getEntryDate());
                System.out.println(journalDTO.getAccountId());
                System.out.println(journalDTO.getCustomerId());
                System.out.println(journalDTO.getSupplierId());
                System.out.println(journalDTO.getVoucherNo());
                System.out.println(journalDTO.getDescription());
                System.out.println(journalDTO.getDebit());
                System.out.println(journalDTO.getCredit());

            }
             if (successCount > 0) {
                // loadDataSet();
                JOptionPane.showMessageDialog(this, "Successfully Saved (" + successCount + ") records.", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Save Failed", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        }
 
    }//GEN-LAST:event_saveBtnActionPerformed
    public void newRow(){
        DefaultTableModel model = (DefaultTableModel) journalTable.getModel();
        
        String todayDate = new java.text.SimpleDateFormat("dd-MM-yyyy").format(new java.util.Date());
        model.addRow(new Object[]{todayDate,"","","","",0,0});

    }
    
    private JTextField customTextField = new JTextField();

    public void setupDynamicDropdowns() {
        // ComboBox များကို Initialize လုပ်ခြင်း
        customerComboBox = new JComboBox<>();
        supplierComboBox = new JComboBox<>();

        // tableModel လည်း ရှိပြီးသားဖြစ်ရပါမည်
        // 💡 ဟောဒီမှာ 'new JTable' မဆောက်တော့ဘဲ ရှိပြီးသား cashTable ထဲကို တိုက်ရိုက် Editor ထည့်ပါမယ်
        journalTable.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(customerComboBox) {
            @Override
            public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {

                // ဘေးနားက 'Particular' (Column Index 1) မှာ ဘာရွေးထားလဲ လှမ်းကြည့်မည်
                Object accountValue = table.getValueAt(row, 1);

                if (accountValue != null) {
                    String accountName = accountValue.toString().trim();

                    // (A) Receivable ဖြစ်လျှင် Customer List ကို DB မှဆွဲထုတ်ပြီး ပြမည်
                    if (accountName.equalsIgnoreCase("Receivable")) {
                        customerComboBox.removeAllItems();
                        List<ComboIdName> customers = customerDAO.getCustomersNamesFromDB();
                        for (ComboIdName name : customers) {
                            customerComboBox.addItem(name);
                        }
                        if (value != null) {
                            customerComboBox.setSelectedItem(value.toString());
                        }
                        return customerComboBox;

                    } // (B) Payable ဖြစ်လျှင် Supplier List ကို DB မှဆွဲထုတ်ပြီး ပြမည်
                    else if (accountName.equalsIgnoreCase("Payable")) {
                        supplierComboBox.removeAllItems();
                        List<ComboIdName> suppliers = supplierDAO.getSuppliersNamesFromDB();
                        for (ComboIdName name : suppliers) {
                            supplierComboBox.addItem(name);

                        }

                        // 💡 Supplier ComboBox ကို ဤနေရာတွင် တိုက်ရိုက် လဲလှယ်ပြသရန်
                        if (value != null) {
                            supplierComboBox.setSelectedItem(value.toString());
                        }
                        return supplierComboBox;
                    }
                }

                // Expense သို့မဟုတ် အခြားစာရင်းဆိုလျှင် နှိပ်ရုံနဲ့ ဘာ dropdown မှ မကျလာစေရန် Component အလွတ်တစ်ခု ပြန်ပေးမည်
                //return new JTextField();
                customTextField.setText(value != null ? value.toString() : "");
                return customTextField;
            }

            @Override
            public Object getCellEditorValue() {
                // လက်ရှိ သုံးနေတဲ့ Component က ကွန်ပျူတာနောက်ကွယ်မှာ ဘာဖြစ်နေလဲ စစ်ဆေးခြင်း
                if (customerComboBox.isShowing()) {
                    return customerComboBox.getSelectedItem();
                } else if (supplierComboBox.isShowing()) {
                    return supplierComboBox.getSelectedItem();
                } else {
                    // အကယ်၍ Dropdown မဟုတ်ဘဲ Text Field ဖြစ်နေလျှင် User ရိုက်ထားသော စာသား (Customize တန်ဖိုး) ကို သိမ်းမည်
                    return customTextField.getText();
                }
            }
        });

        
        
    }
    
    public void debitOrCreditClose(){
        // Table ထဲက ဒေတာ အပြောင်းအလဲဖြစ်တိုင်း လှမ်းတွက်မည့် Listener
journalTable.getModel().addTableModelListener(new javax.swing.event.TableModelListener() {
    private boolean isUpdating = false; // Infinite Loop မဖြစ်စေရန် တားဆီးသည့် Flag

    @Override
    public void tableChanged(javax.swing.event.TableModelEvent e) {
        if (isUpdating) return; // ကုဒ်ကနေ ပြန်ပြင်နေချိန်ဆိုလျှင် ကျော်မည်
        
        int row = e.getFirstRow();
        int column = e.getColumn();
        
        // Debit (Index 5) သို့မဟုတ် Credit (Index 6) ကို ပြင်မိမှသာ တွက်ချက်မည်
        if (column == 5 || column == 6) {
            isUpdating = true;
            try {
                DefaultTableModel model = (DefaultTableModel) journalTable.getModel();
                
                // ဒေတာများကို ရယူခြင်း
                double debit = 0.0;
                double credit = 0.0;
                
                Object debitVal = model.getValueAt(row, 5);
                Object creditVal = model.getValueAt(row, 6);
                
                if (debitVal != null && !debitVal.toString().trim().isEmpty()) {
                    debit = Double.parseDouble(debitVal.toString().trim());
                }
                if (creditVal != null && !creditVal.toString().trim().isEmpty()) {
                    credit = Double.parseDouble(creditVal.toString().trim());
                }

                // 🚀 Logic ၁။ Debit ရိုက်လျှင် Credit ကို ဝိုင်ပစ်၊ Credit ရိုက်လျှင် Debit ကို ဝိုင်ပစ်
                if (column == 5 && debit > 0) {
                    model.setValueAt(0.0, row, 6); // Credit ကို 0.0 ပြန်ပြောင်း
                    credit = 0.0;
                } else if (column == 6 && credit > 0) {
                    model.setValueAt(0.0, row, 5); // Debit ကို 0.0 ပြန်ပြောင်း
                    debit = 0.0;
                }

                // 🚀 Logic ၂။ Balance ကို Row အားလုံးအတွက် Cumulative Carry Forward ပြန်တွက်ခြင်း
              //  updateRunningBalance();

            } catch (NumberFormatException ex) {
                // ဂဏန်းမဟုတ်တာ ရိုက်ထည့်မိပါက လက်ခံမည်မဟုတ်ကြောင်း ပြသရန်
            } finally {
                isUpdating = false;
            }
        }
    }
});
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton deleteRowBtn;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable journalTable;
    private javax.swing.JButton newRowBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
